---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monitoring-source-prometheus-stack
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: main
  url: http://github.com/fluxcd/flux2
